package com.apiweb.backend.Model.ENUM;

public enum Categoria {
    DESARROLLO_WEB,
    BASES_DE_DATOS_RELACIONALES,
    BASES_DE_DATOS_NOSQL,
    PROGRAMACION,
    ANALITICA_DE_DATOS,
    VISUALIZACION_DE_DATOS,
    INTELIGENCIA_ARTIFICIAL,
    MACHINE_LEARNING;
}
