package com.apiweb.backend.Enum;

public enum CategoriaEnum {
    DESARROLLO_WEB,
    BASES_DE_DATOS_RELACIONALES,
    BASES_DE_DATOS_NOSQL,
    PROGRAMACION,
    ANALITICA_DE_DATOS,
    VISUALIZACION_DE_DATOS,
    INTELIGENCIA_ARTIFICIAL,
    MACHINE_LEARNING;
}
